[package]
name = "clickcapture"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.24"
once_cell = "1.19"
lopdf = "0.27"
num-format = "0.4.4"

[dependencies.windows]
version = ">=0.60, <=0.62"
features = [
    "Win32_Graphics_Gdi",
    "Win32_Graphics_GdiPlus",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Controls",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Foundation",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Memory",
    "Win32_Media_KernelStreaming",
]

[build-dependencies]
winres = "0.1"
embed-resource = "2.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true